version: "3.8"
services:
  pvpgn-armlinux:
    # image: pvpgn-armlinux
    build:
      # context: ./
      dockerfile: server-diabolico.Dockerfile
    # environment:
    #  - LANG=en
    #  - WG_HOST=193.123.103.35
    #  - WG_DEVICE=enp0s6
    # image: ghcr.io/wg-easy/wg-easy
    # container_name: pvpgn-armlinux
    # hostname: pvpgn-armlinux
    #volumes:
    #  - ~/.wg-easy:/etc/wireguard
    ports:
      - "6112-6114:6112-6114" # Feb 22 01:38:44 [info ] _setup_listensock: listening for bnet connections on 0.0.0.0:6112 TCP
      - "6200:6200" # Feb 22 01:38:44 [info ] _setup_listensock: listening for w3route connections on 0.0.0.0:6200 TCP 
      - "4000:4000"
      - "16112:16112"
      - "8888:8888"
      # 6112-6114,6200,4000,16112,8888
# docker run -it -p 6112:6112 -p 4000:4000 -v /ruta/a/tu/config:/etc/pvpgn -v /ruta/a/tus/datos:/var/pvpgn pvpgn-server
#    restart: unless-stopped
#    cap_add:
#      - NET_ADMIN
#      - SYS_MODULE
#    sysctls:
#      - net.ipv4.ip_forward=1
#      - net.ipv4.conf.all.src_valid_mark=1
#    networks: 
#      wg_easy_vlan:
#        ipv4_address: 192.168.133.142
networks:
  nginx_vlan:
    driver: macvlan
    driver_opts:
      parent: enp4s0
    ipam:
      driver: default
      config:
        - subnet: 192.168.133.0/24
          gateway: 192.168.133.1